name: Synchronizes this fork with the official repository
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream Repo Fork
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: "https://github.com/bminor/binutils-gdb.git"
          upstream_branch: "master"
          downstream_branch: ""
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch_args: ""
          merge_args: ""
          push_args: ""
          spawn_logs: "false"